Add decedent fetus
HL7/fhir-bfdr pull request #6
Opened 2023-11-15 17:03 UTC by ptran265

- added patientDecedentFetus profile and examples (moved from VRCL)

2023-11-15 17:24 UTC, rpassas approved these changes

2023-11-15 21:22 UTC, saulakravitz commented on input/fsh/profiles/PatientDecedentFetus.fsh
Perhaps the multiple births should be added to PatientVitalRecords?

2023-11-15 21:27 UTC, saulakravitz commented on input/fsh/rulesets/DEF_Rulesets.fsh
> +    * ^binding.description = "Plurality Edit Flags (NCHS)"
I don't think this is right...
MultipleBirth should have two expensions:
  1) edit flag
  2) [http://hl7.org/fhir/StructureDefinition/patient-multipleBirthTotal](http://hl7.org/fhir/extensions/1.0.0/StructureDefinition-patient-multipleBirthTotal.html)

2023-11-15 21:28 UTC, saulakravitz commented on input/fsh/rulesets/DEF_Rulesets.fsh
> +    * ^short = "To reflect the relevant edit possibilities for plurality."
Unless this is used multiple times, it should just be incorporated into PatientVitalRecords, or PatientChildVitalRecords.

2023-11-15 21:29 UTC, saulakravitz requested changes
See my comments

2023-11-17 15:47 UTC, saulakravitz approved these changes

2023-11-17 15:47 UTC, merged