Differentiate Encounters
HL7/fhir-bfdr pull request #67
Opened 2024-01-05 16:54 UTC by saulakravitz

Added a role extension to both the Maternity and Birth Encounters to make them trivial to pull out of the bundle without resort to reference chasing.

2024-01-05 22:52 UTC, rpassas approved these changes

2024-01-05 22:55 UTC, rpassas requested changes
Need to add these roles to examples

2024-01-08 13:44 UTC, ptran265 reviewed
you could also make a note in the content transitions page that this extension was added for EncounterBirth and EncounterMaternity profiles

2024-01-08 20:50 UTC, saulakravitz commented
> Need to add these roles to examples

They are built into the profiles, so they automagically show up in the examples.

2024-01-08 22:50 UTC, merged